MODEL:
  TYPE: generalized_rcnn
  CONV_BODY: ResNet.ResNet50_conv4_body
  FASTER_RCNN: True
  LOAD_IMAGENET_PRETRAINED_WEIGHTS: False
NUM_GPUS: 8
RESNETS:
  FREEZE_AT: 3 #2
  #IMAGENET_PRETRAINED_WEIGHTS: 'data/pretrained_model/resnet50_caffe.pth'
SOLVER:
  WEIGHT_DECAY: 0.0001
  LR_POLICY: steps_with_decay
  BASE_LR: 0.002 # 0.01
  GAMMA: 0.1
  # 1x schedule (note TRAIN.IMS_PER_BATCH: 1)
  MAX_ITER: 60000 #36000
  STEPS: [0, 56000, 60000] #[0, 24000, 32000]
RPN:
  SIZES: (32, 64, 128, 256, 512)
FAST_RCNN:
  ROI_BOX_HEAD: ResNet.ResNet_roi_conv5_head
  ROI_XFORM_METHOD: RoIAlign
TRAIN:
  SCALES: (600,) #(800,)
  MAX_SIZE: 1000 #1333
  IMS_PER_BATCH: 1
  BATCH_SIZE_PER_IM: 128 #512 #256 #512
TEST:
  SCALE: 600 #800
  MAX_SIZE: 1000 #1333
  NMS: 0.5
  RPN_PRE_NMS_TOP_N: 6000
  RPN_POST_NMS_TOP_N: 300 #300
